// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiLLbun-iegk7zQUh26-K_uk9AiiTYevI',
    appId: '1:304752004739:web:b1755106c115644053d5b6',
    messagingSenderId: '304752004739',
    projectId: 'star-aera',
    authDomain: 'star-aera.firebaseapp.com',
    storageBucket: 'star-aera.appspot.com',
    measurementId: 'G-KTZYCQ46BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIBea8pfWVmHq5Hi4VZQFpnCFWnAeXoxM',
    appId: '1:304752004739:android:e97bb2e420d7d84953d5b6',
    messagingSenderId: '304752004739',
    projectId: 'star-aera',
    storageBucket: 'star-aera.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMl8IUn5f42cZMfxZefkA-oNMkdKZV5pA',
    appId: '1:304752004739:ios:a6136674b948e63a53d5b6',
    messagingSenderId: '304752004739',
    projectId: 'star-aera',
    storageBucket: 'star-aera.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMl8IUn5f42cZMfxZefkA-oNMkdKZV5pA',
    appId: '1:304752004739:ios:a6136674b948e63a53d5b6',
    messagingSenderId: '304752004739',
    projectId: 'star-aera',
    storageBucket: 'star-aera.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiLLbun-iegk7zQUh26-K_uk9AiiTYevI',
    appId: '1:304752004739:web:44b97a9af1538db953d5b6',
    messagingSenderId: '304752004739',
    projectId: 'star-aera',
    authDomain: 'star-aera.firebaseapp.com',
    storageBucket: 'star-aera.appspot.com',
    measurementId: 'G-V3SYWCF55N',
  );

}